// lib/pwa/recipes-data.ts
// 60 recetas reales del Protocolo Anti-Hinchazón
// 35 básicas (Front - protocolo 7 días) + 25 extra (Bump - recetario)

export type Moment = 'desayuno' | 'almuerzo' | 'cena' | 'snack';
export type Difficulty = 'fácil' | 'media';

import { DietaryTags } from './dietary-preferences';

export interface Recipe {
  id: string;
  name: string;
  moment: Moment;
  time: string;
  difficulty: Difficulty;
  ingredients: string[];
  steps: string[];
  tip: string;
  isExtra: boolean; // true = bump (recetas 36-60)
  isExpress: boolean; // true = ≤ 10 min (Kit Anti-Excusas)
  imageSlot: string; // emoji placeholder
  dietaryTags: DietaryTags;
}

export const recipes: Recipe[] = [
  // ═══════════════════════════════════════════════
  // DÍA 1 — 5 recetas básicas (Front)
  // ═══════════════════════════════════════════════
  {
    id: 'dia1-desayuno',
    name: 'Yogur Natural con Kiwi y Chía',
    moment: 'desayuno',
    time: '5 min',
    difficulty: 'fácil',
    ingredients: [
      '1 vaso de yogur natural sin azúcar (o kéfir de agua / yogur de coco)',
      '1 kiwi en cubos',
      '1 cucharada de chía',
      '½ cucharadita de miel cruda (opcional)',
    ],
    steps: [
      'Volcá el yogur en un bowl o vaso amplio.',
      'Cortá el kiwi en cubos y distribuilo arriba.',
      'Espolvoreá la cucharada de chía.',
      'Si querés un toque dulce, agregá la miel cruda.',
      'Consumí de inmediato o dejá reposar 5 min para que la chía se hidrate.',
    ],
    tip: 'La combinación chía + kiwi mejora el tránsito intestinal en menos de 24 horas. El kiwi aporta actinidina, una enzima que facilita la digestión de proteínas.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥣',
    dietaryTags: { isGlutenFree: true, isDairyFree: false, isVegetarian: true },
  },
  {
    id: 'dia1-snack-am',
    name: 'Manzana Verde con Almendras',
    moment: 'snack',
    time: '2 min',
    difficulty: 'fácil',
    ingredients: [
      '1 manzana verde',
      '6 almendras naturales sin sal',
    ],
    steps: [
      'Lavá y cortá la manzana en gajos.',
      'Acompañá con las 6 almendras.',
      'Comé despacio, masticando bien cada bocado.',
    ],
    tip: 'La manzana verde tiene más pectina (fibra soluble) que la roja, lo que alimenta tu microbiota positiva. Las almendras aportan grasas buenas que dan saciedad real.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍏',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia1-almuerzo',
    name: 'Bowl de Quinoa con Salmón y Palta',
    moment: 'almuerzo',
    time: '20 min',
    difficulty: 'media',
    ingredients: [
      '½ taza de quinoa',
      '1 filete de salmón',
      '½ palta en cubos',
      'Hojas de espinaca cruda',
      'Tomate cherry',
      'Aceite de oliva, limón y sal',
    ],
    steps: [
      'Cociná la quinoa: ½ taza con 1 taza de agua, hervir y cocinar 10 min.',
      'Mientras, cociná el salmón a la plancha con sal y limón, 4 min por lado.',
      'Desmenuzá el salmón con tenedor.',
      'Armá el bowl: quinoa de base, salmón, palta en cubos, espinaca y tomate cherry.',
      'Aliñá con aceite de oliva + limón + sal.',
    ],
    tip: 'El salmón aporta EPA y DHA (omega-3), los antiinflamatorios más potentes que podés comer. Combinado con la palta, maximizás la absorción de nutrientes.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🐟',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },
  {
    id: 'dia1-snack-pm',
    name: 'Té Verde con Chocolate 70%',
    moment: 'snack',
    time: '3 min',
    difficulty: 'fácil',
    ingredients: [
      '1 saquito de té verde',
      '2 cuadraditos de chocolate amargo 70%',
      'Agua caliente',
    ],
    steps: [
      'Calentá agua sin que llegue a hervir fuerte.',
      'Preparate el té verde y dejalo infusionar 3 minutos.',
      'Acompañá con los 2 cuadraditos de chocolate amargo.',
    ],
    tip: 'La cafeína del té verde es más suave que la del café y no genera el rebote de cortisol. Las catequinas (EGCG) son potentes antiinflamatorios.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍵',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia1-cena',
    name: 'Crema de Calabaza con Jengibre y Huevo Poché',
    moment: 'cena',
    time: '25 min',
    difficulty: 'media',
    ingredients: [
      '2 tazas de calabaza en cubos',
      '1 trozo de jengibre fresco rallado',
      '1 diente de ajo',
      '1 huevo',
      'Vinagre, sal, pimienta y perejil',
    ],
    steps: [
      'Herví la calabaza en cubos con el jengibre rallado y el ajo durante 15 min.',
      'Procesá todo con minipimer hasta obtener una crema suave.',
      'Salpimentá a gusto.',
      'Para el huevo poché: herví agua con un chorro de vinagre. Hacé un remolino y volcá el huevo. Cociná 3 min.',
      'Serví la crema con el huevo poché arriba y perejil picado.',
    ],
    tip: 'El jengibre fresco acelera el vaciado gástrico y reduce la sensación de distensión en menos de 30 minutos. Ideal como cena liviana.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥘',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },


  // ═══════════════════════════════════════════════
  // DÍA 2 — 5 recetas básicas (Front)
  // ═══════════════════════════════════════════════
  {
    id: 'dia2-desayuno',
    name: 'Avena Tibia con Banana, Lino y Canela',
    moment: 'desayuno',
    time: '8 min',
    difficulty: 'fácil',
    ingredients: [
      '½ taza de avena tradicional (no instantánea)',
      '1 taza de leche de almendras o agua',
      '1 banana en rodajas',
      '1 cucharadita de lino molido',
      'Canela a gusto',
      '4 nueces picadas (opcional)',
    ],
    steps: [
      'Cociná la avena con la leche de almendras a fuego medio, revolviendo 5 min.',
      'Apagá el fuego.',
      'Agregá la banana en rodajas encima.',
      'Espolvoreá el lino molido y la canela.',
      'Si querés, sumá las nueces picadas.',
    ],
    tip: 'La avena tradicional (no instantánea) tiene fibra beta-glucano que alimenta las bacterias buenas. El lino molido libera omega-3 directamente en el intestino.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥣',
    dietaryTags: { isGlutenFree: false, isDairyFree: false, isVegetarian: true },
  },
  {
    id: 'dia2-snack-am',
    name: 'Pera con Nueces',
    moment: 'snack',
    time: '1 min',
    difficulty: 'fácil',
    ingredients: [
      '1 pera madura',
      '5 nueces',
    ],
    steps: [
      'Lavá y cortá la pera en gajos.',
      'Acompañá con las 5 nueces.',
      'Masticá bien cada bocado.',
    ],
    tip: 'La pera tiene fibra soluble que alimenta tu microbiota. Las nueces son la única nuez con ALA (omega-3 vegetal). Combo simple, máxima saciedad.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍐',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia2-almuerzo',
    name: 'Wrap de Hojas Verdes con Pollo y Palta',
    moment: 'almuerzo',
    time: '15 min',
    difficulty: 'fácil',
    ingredients: [
      '1 pechuga de pollo',
      '4 hojas grandes de lechuga mantecosa',
      '½ palta en láminas',
      'Tomate, zanahoria rallada, brotes de alfalfa',
      'Aliño: yogur natural + limón + mostaza Dijon',
    ],
    steps: [
      'Cociná la pechuga a la plancha 8 min y cortala en tiras.',
      'Lavá y secá bien las hojas de lechuga.',
      'Rellená cada hoja con pollo, palta, tomate, zanahoria y brotes.',
      'Preparé el aliño mezclando yogur + limón + mostaza.',
      'Rocía el aliño, cerrá los wraps y servir.',
    ],
    tip: 'Usar lechuga en lugar de tortilla de trigo elimina el gluten y agrega fibra soluble que alimenta tu microbiota positiva.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥬',
    dietaryTags: { isGlutenFree: true, isDairyFree: false, isVegetarian: false },
  },
  {
    id: 'dia2-snack-pm',
    name: 'Kéfir con Frutos Rojos',
    moment: 'snack',
    time: '1 min',
    difficulty: 'fácil',
    ingredients: [
      '1 vaso de kéfir (de leche o de agua)',
      '1 puñado de frutos rojos congelados (frutillas, arándanos, frambuesas)',
    ],
    steps: [
      'Volcá el kéfir en un vaso.',
      'Agregá los frutos rojos congelados encima.',
      'Mezclá suavemente y consumí de inmediato.',
    ],
    tip: 'El kéfir tiene entre 10 y 34 cepas de bacterias probióticas vivas, versus las 2-3 del yogur común. Es el snack más amigable para la microbiota.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥛',
    dietaryTags: { isGlutenFree: true, isDairyFree: false, isVegetarian: true },
  },
  {
    id: 'dia2-cena',
    name: 'Sopa de Verduras con Tortilla de Espinaca',
    moment: 'cena',
    time: '25 min',
    difficulty: 'media',
    ingredients: [
      '1 cebolla, 1 zanahoria, 1 puerro, 1 zucchini',
      'Aceite de oliva, caldo casero o agua + sal',
      '2 huevos',
      '1 taza de espinaca cocida y picada',
      'Sal, pimienta',
    ],
    steps: [
      'Rehogá la cebolla, zanahoria, puerro y zucchini picados en aceite de oliva 5 min.',
      'Cubrí con caldo o agua + sal. Cociná 15 min.',
      'Procesá si querés crema o dejá rústica.',
      'Para la tortilla: batí 2 huevos, agregá la espinaca cocida, sal y pimienta.',
      'Cociná en sartén con poco aceite, 5 min cada lado.',
      'Serví la sopa con la tortilla cortada al costado.',
    ],
    tip: 'La espinaca aporta magnesio que regula el cortisol. Menos cortisol = menos inflamación sistémica. Ideal como cena caliente y liviana.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍲',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },


  // ═══════════════════════════════════════════════
  // DÍA 3 — 5 recetas básicas (Front)
  // ═══════════════════════════════════════════════
  {
    id: 'dia3-desayuno',
    name: 'Smoothie Verde Anti-Hinchazón',
    moment: 'desayuno',
    time: '5 min',
    difficulty: 'fácil',
    ingredients: [
      '1 taza de espinaca cruda',
      '½ banana',
      '½ pepino sin cáscara',
      '1 cucharadita de jengibre fresco rallado',
      'Jugo de ½ limón',
      '1 cucharada de chía',
      '1 vaso de agua de coco o agua común',
    ],
    steps: [
      'Lavá la espinaca y el pepino.',
      'Cortá el pepino y la banana en trozos.',
      'Colocá todos los ingredientes en la licuadora: líquido primero, sólidos después.',
      'Procesá 30 segundos a velocidad alta.',
      'Tomalo enseguida para preservar los nutrientes.',
    ],
    tip: 'El jengibre fresco es 6 veces más potente que el jengibre en polvo. La chía forma un gel que protege la mucosa intestinal.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥤',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia3-snack-am',
    name: 'Papaya con Limón',
    moment: 'snack',
    time: '2 min',
    difficulty: 'fácil',
    ingredients: [
      '1 taza de papaya/mamón en cubos',
      'Jugo de limón',
    ],
    steps: [
      'Pelá la papaya y cortala en cubos.',
      'Rociá con jugo de limón fresco.',
      'Comé de inmediato para aprovechar las enzimas.',
    ],
    tip: 'La papaína es la enzima digestiva más potente de estos 7 días. Si no conseguís papaya, reemplazá por ananá fresco.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍈',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia3-almuerzo',
    name: 'Salmón al Horno con Brócoli y Batata',
    moment: 'almuerzo',
    time: '25 min',
    difficulty: 'media',
    ingredients: [
      '1 filete de salmón',
      '1 taza de brócoli en floretes',
      '1 batata/camote en cubos',
      'Limón, eneldo, aceite de oliva',
      'Romero, pimentón, sal',
    ],
    steps: [
      'Precalentá el horno a 200°C.',
      'Colocá la batata en cubos en la fuente con aceite, romero y pimentón. Horneá 10 min.',
      'Agregá el salmón con limón, eneldo y aceite. Sumá el brócoli.',
      'Horneá todo junto 12 min más.',
      'Serví cuando el salmón se desmigue fácilmente.',
    ],
    tip: 'El brócoli contiene sulforafano, un compuesto que activa genes de defensa antioxidante en el intestino. Cociná al vapor para preservarlo.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🐟',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },
  {
    id: 'dia3-snack-pm',
    name: 'Hummus Casero con Bastones de Zanahoria y Apio',
    moment: 'snack',
    time: '5 min',
    difficulty: 'fácil',
    ingredients: [
      '1 lata de garbanzos escurridos',
      '2 cdas de tahini',
      'Jugo de 1 limón',
      '1 diente de ajo, sal, aceite de oliva',
      'Zanahorias y apio en bastones',
    ],
    steps: [
      'Procesá garbanzos + tahini + limón + ajo + sal + aceite hasta obtener crema.',
      'Si queda espeso, agregá 2-3 cdas del líquido de los garbanzos.',
      'Cortá zanahoria y apio en bastones.',
      'Serví el hummus en un bowl con los bastones al costado.',
    ],
    tip: 'Los garbanzos son ricos en butirato (preforma), que nutre directamente las células del colon. El tahini aporta calcio y vitamina E antioxidante.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥕',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia3-cena',
    name: 'Ensalada Tibia de Quinoa con Huevo Duro',
    moment: 'cena',
    time: '20 min',
    difficulty: 'fácil',
    ingredients: [
      '½ taza de quinoa cocida',
      'Rúcula y espinaca',
      'Tomate cherry, pepino',
      '1 huevo duro picado',
      'Semillas de girasol',
      'Aceite de oliva + limón + sal + pizca de cúrcuma',
    ],
    steps: [
      'Cociná la quinoa si no la tenés lista (10 min en agua).',
      'Herví el huevo 10 min, pelá y picá.',
      'Armá la ensalada: rúcula y espinaca de base, quinoa, tomate cherry, pepino.',
      'Agregá el huevo duro picado y semillas de girasol.',
      'Aliñá con aceite de oliva, limón, sal y cúrcuma.',
    ],
    tip: 'La cúrcuma en el aliño, combinada con el aceite de oliva (grasa), mejora drásticamente la absorción de curcumina antiinflamatoria.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥗',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },


  // ═══════════════════════════════════════════════
  // DÍA 4 — 5 recetas básicas (Front)
  // ═══════════════════════════════════════════════
  {
    id: 'dia4-desayuno',
    name: 'Tostadas de Centeno con Palta y Tomate',
    moment: 'desayuno',
    time: '7 min',
    difficulty: 'fácil',
    ingredients: [
      '2 rebanadas de pan de centeno integral (o masa madre)',
      '½ palta',
      'Limón, sal y pimienta',
      'Rodajas finas de tomate',
      'Orégano fresco y semillas de sésamo',
    ],
    steps: [
      'Tostá las rebanadas de pan hasta que estén crocantes.',
      'Pisá la palta con limón, sal y pimienta.',
      'Untá la palta sobre cada tostada.',
      'Colocá rodajas finas de tomate arriba.',
      'Terminá con orégano fresco y semillas de sésamo.',
    ],
    tip: 'El pan de centeno integral tiene fermentación larga que reduce el contenido de FODMAPs, haciéndolo mucho más digerible que el pan blanco.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍞',
    dietaryTags: { isGlutenFree: false, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia4-snack-am',
    name: 'Yogur con Miel Cruda y Cúrcuma',
    moment: 'snack',
    time: '2 min',
    difficulty: 'fácil',
    ingredients: [
      '1 vaso de yogur natural sin azúcar',
      '½ cucharadita de miel cruda',
      '¼ cucharadita de cúrcuma',
      'Pizca de pimienta negra',
    ],
    steps: [
      'Volcá el yogur en un vaso o bowl.',
      'Agregá la miel cruda, la cúrcuma y la pimienta negra.',
      'Mezclá bien hasta integrar.',
      'Consumí de inmediato.',
    ],
    tip: 'La pimienta negra multiplica la absorción de curcumina por 20 veces. Siempre combiná cúrcuma con pimienta negra.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥛',
    dietaryTags: { isGlutenFree: true, isDairyFree: false, isVegetarian: true },
  },
  {
    id: 'dia4-almuerzo',
    name: 'Bowl de Pollo con Arroz Integral y Verduras Asadas',
    moment: 'almuerzo',
    time: '20 min',
    difficulty: 'media',
    ingredients: [
      '½ taza de arroz integral cocido',
      '1 pechuga de pollo',
      'Pimientos rojos, zucchini, cebolla morada',
      'Aceite de oliva, cúrcuma, comino, sal',
      'Aliño: tahini + limón + agua + sal',
    ],
    steps: [
      'Cociná el pollo a la plancha con cúrcuma, comino y sal, 8 min.',
      'Cortá los vegetales y asalos al horno con aceite de oliva 15 min a 200°C.',
      'Cortá el pollo en cubos.',
      'Armá el bowl: arroz de base, pollo, vegetales asados.',
      'Aliñá con tahini + limón + agua + sal.',
    ],
    tip: 'El arroz integral cocido y enfriado genera almidón resistente, un prebiótico que alimenta bacterias beneficiosas del colon.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍗',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },
  {
    id: 'dia4-snack-pm',
    name: 'Té de Jengibre con Nueces',
    moment: 'snack',
    time: '5 min',
    difficulty: 'fácil',
    ingredients: [
      '2 rodajas de jengibre fresco',
      'Agua caliente',
      'Medio limón exprimido',
      '5 nueces',
    ],
    steps: [
      'Herví las rodajas de jengibre en agua durante 5 min.',
      'Colá y volcá en una taza.',
      'Sumá el medio limón exprimido.',
      'Tomalo caliente con las 5 nueces al lado.',
    ],
    tip: 'Este es el snack más antiinflamatorio del plan. El gingerol del jengibre fresco + los omega-3 de las nueces = doble acción antiinflamatoria.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍵',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia4-cena',
    name: 'Pescado Blanco al Limón con Zucchini Grillado',
    moment: 'cena',
    time: '22 min',
    difficulty: 'fácil',
    ingredients: [
      '1 filete de merluza, lenguado o tilapia',
      'Limón, ajo, perejil y aceite de oliva',
      '2 zucchinis en rodajas',
      'Sal, pimienta',
      'Ensalada de hojas verdes',
    ],
    steps: [
      'Precalentá el horno a 200°C.',
      'Colocá el pescado en fuente con limón, ajo laminado, perejil y aceite.',
      'Horneá 10 min.',
      'Mientras, grillá el zucchini en rodajas en sartén caliente, 4 min por lado.',
      'Serví el pescado con zucchini y ensalada de hojas verdes.',
    ],
    tip: 'El pescado blanco es ultra liviano para la cena: proteína de alta calidad sin la grasa que ralentiza la digestión nocturna.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🐟',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },


  // ═══════════════════════════════════════════════
  // DÍA 5 — 5 recetas básicas (Front)
  // ═══════════════════════════════════════════════
  {
    id: 'dia5-desayuno',
    name: 'Bowl de Papaya, Chía y Kiwi',
    moment: 'desayuno',
    time: '5 min',
    difficulty: 'fácil',
    ingredients: [
      '1 taza de papaya en cubos',
      '1 kiwi en rodajas',
      '1 cda de chía hidratada (10 min antes en 3 cdas de agua)',
      '1 cdita de coco rallado sin azúcar',
      'Chorrito de jugo de naranja (opcional)',
    ],
    steps: [
      'Hidratá la chía en agua o leche vegetal 10 min antes.',
      'Cortá la papaya en cubos y el kiwi en rodajas.',
      'Armá el bowl: papaya de base, kiwi, chía hidratada.',
      'Espolvoreá el coco rallado.',
      'Si querés, agregá un chorrito de jugo de naranja.',
    ],
    tip: 'La papaya en ayunas activa la papaína, enzima que descompone proteínas inflamatorias. Combinada con kiwi (actinidina) tenés un doble boost digestivo.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍈',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia5-snack-am',
    name: 'Almendras con Chocolate 70%',
    moment: 'snack',
    time: '1 min',
    difficulty: 'fácil',
    ingredients: [
      '8 almendras',
      '2 cuadraditos de chocolate 70%',
    ],
    steps: [
      'Tomá las almendras y el chocolate.',
      'Comé despacio, alternando.',
      'Llevalo en un frasquito como snack portátil.',
    ],
    tip: 'El cacao 70%+ es rico en polifenoles que alimentan las bifidobacterias del intestino. Las almendras aportan vitamina E antioxidante.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍫',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia5-almuerzo',
    name: 'Lentejas Guisadas con Verduras',
    moment: 'almuerzo',
    time: '25 min',
    difficulty: 'media',
    ingredients: [
      '1 taza de lentejas cocidas (o lata escurrida)',
      'Cebolla, ajo, zanahoria, morrón rojo',
      'Tomate picado',
      'Comino, cúrcuma, sal, pimienta',
      'Caldo de verduras',
      'Perejil fresco',
    ],
    steps: [
      'Rehogá cebolla, ajo, zanahoria y morrón en aceite de oliva 5 min.',
      'Sumá las lentejas, tomate picado, comino y cúrcuma.',
      'Cubrí con caldo de verduras.',
      'Cociná 15 min a fuego bajo.',
      'Serví con perejil fresco arriba.',
    ],
    tip: 'Las lentejas son una de las mejores fuentes de fibra prebiótica. El comino reduce la producción de gas durante la digestión de legumbres.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥘',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia5-snack-pm',
    name: 'Manzana Asada con Canela y Nueces',
    moment: 'snack',
    time: '7 min',
    difficulty: 'fácil',
    ingredients: [
      '1 manzana',
      'Canela',
      '4 nueces picadas',
    ],
    steps: [
      'Cortá la manzana en 8 gajos.',
      'Espolvoreá canela generosamente.',
      'Cociná en microondas 4 min o sartén tapada con un toque de agua 7 min.',
      'Serví caliente con las nueces picadas arriba.',
    ],
    tip: 'La manzana cocida libera más pectina que la cruda, alimentando mejor tu microbiota. La canela estabiliza los niveles de azúcar en sangre.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍎',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia5-cena',
    name: 'Tortilla de Zucchini al Horno con Ensalada Verde',
    moment: 'cena',
    time: '25 min',
    difficulty: 'media',
    ingredients: [
      '2 zucchinis grandes rallados',
      '3 huevos batidos',
      '2 cdas de queso rallado (opcional)',
      'Perejil, sal, pimienta',
      'Rúcula, espinaca y tomate para ensalada',
    ],
    steps: [
      'Rallá los zucchinis, salalos y dejalos escurrir 10 min.',
      'Exprimí con las manos para sacar el exceso de agua.',
      'Mezclá con los huevos batidos, queso, perejil, sal y pimienta.',
      'Volcá en fuente y horneá 18 min a 180°C.',
      'Serví con ensalada de rúcula, espinaca y tomate.',
    ],
    tip: 'El zucchini es uno de los vegetales más suaves para el intestino: bajo en FODMAPs, alto en agua y potasio. Perfecto para cenas livianas.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥚',
    dietaryTags: { isGlutenFree: true, isDairyFree: false, isVegetarian: true },
  },


  // ═══════════════════════════════════════════════
  // DÍA 6 — 5 recetas básicas (Front)
  // ═══════════════════════════════════════════════
  {
    id: 'dia6-desayuno',
    name: 'Huevos Revueltos con Espinaca y Tomate',
    moment: 'desayuno',
    time: '8 min',
    difficulty: 'fácil',
    ingredients: [
      '2 huevos',
      '1 taza de espinaca cruda',
      '½ tomate en cubos',
      'Aceite de oliva',
      '1 rebanada de pan de centeno tostado',
    ],
    steps: [
      'Calentá un chorrito de aceite de oliva en sartén.',
      'Agregá la espinaca y cociná hasta que se reduzca (1 min).',
      'Volcá los huevos batidos y revolvé suavemente.',
      'Apagá cuando estén cremosos, no secos.',
      'Sumá el tomate en cubos arriba. Serví con el pan tostado.',
    ],
    tip: 'Los huevos aportan colina, nutriente esencial para la integridad de la mucosa intestinal. La espinaca suma magnesio antiinflamatorio.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍳',
    dietaryTags: { isGlutenFree: false, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia6-snack-am',
    name: 'Smoothie de Ananá y Jengibre',
    moment: 'snack',
    time: '3 min',
    difficulty: 'fácil',
    ingredients: [
      '1 taza de ananá (fresco o congelado)',
      '1 cdita de jengibre rallado',
      '½ pepino',
      'Jugo de ½ limón',
      '1 vaso de agua',
    ],
    steps: [
      'Colocá todos los ingredientes en la licuadora.',
      'Procesá 30 segundos a velocidad alta.',
      'Tomalo de inmediato.',
    ],
    tip: 'El ananá contiene bromelina, enzima que reduce la inflamación intestinal. Combinada con jengibre, es un diurético natural que deshincha rápido.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍍',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia6-almuerzo',
    name: 'Bowl de Pollo Grillado con Quinoa y Palta',
    moment: 'almuerzo',
    time: '20 min',
    difficulty: 'media',
    ingredients: [
      '1 pechuga de pollo',
      'Cúrcuma, comino, sal',
      '½ taza de quinoa cocida',
      '½ palta en cubos',
      'Pepino picado, tomate cherry, hojas verdes',
      'Aliño: tahini + limón + agua + ajo rallado',
    ],
    steps: [
      'Condimentá el pollo con cúrcuma, comino y sal.',
      'Grillá a la plancha 5-6 min por lado.',
      'Cortá en tiras o cubos.',
      'Armá el bowl: quinoa, pollo, palta, pepino, tomate y hojas verdes.',
      'Aliñá con tahini + limón + agua + ajo rallado.',
    ],
    tip: 'La quinoa es uno de los pocos granos completos en aminoácidos. Sin gluten y con fibra prebiótica que nutre tu microbiota.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥗',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },
  {
    id: 'dia6-snack-pm',
    name: 'Yogur con Frutos Rojos y Semillas',
    moment: 'snack',
    time: '1 min',
    difficulty: 'fácil',
    ingredients: [
      '1 vaso de yogur natural',
      '½ taza de frutos rojos',
      '1 cdita de semillas de girasol o calabaza',
    ],
    steps: [
      'Volcá el yogur en un vaso.',
      'Agregá los frutos rojos.',
      'Espolvoreá las semillas encima.',
      'Consumí de inmediato.',
    ],
    tip: 'Los frutos rojos son de las frutas con mayor contenido de polifenoles antiinflamatorios y menor índice glucémico. Combo perfecto con probióticos.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🫐',
    dietaryTags: { isGlutenFree: true, isDairyFree: false, isVegetarian: true },
  },
  {
    id: 'dia6-cena',
    name: 'Wok de Vegetales con Tofu o Pollo',
    moment: 'cena',
    time: '20 min',
    difficulty: 'media',
    ingredients: [
      'Ajo y jengibre rallado',
      'Brócoli, pimientos, zanahoria en juliana, hongos',
      'Tofu en cubos (o pollo previamente cocido)',
      'Salsa de soja baja en sodio o tamari',
      '½ taza de arroz integral (opcional)',
    ],
    steps: [
      'En wok o sartén grande, sofreí ajo y jengibre rallado 1 min.',
      'Sumá brócoli, pimientos, zanahoria y hongos. Cociná 5 min revolviendo.',
      'Agregá el tofu en cubos (o pollo cocido) y un chorrito de tamari.',
      'Cociná 3 min más.',
      'Serví solo o con ½ taza de arroz integral.',
    ],
    tip: 'El jengibre en el wok no solo da sabor: acelera el vaciado gástrico y previene la pesadez post-cena. El tamari (soja sin gluten) es mejor que la salsa de soja común.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥘',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },


  // ═══════════════════════════════════════════════
  // DÍA 7 — 5 recetas básicas (Front)
  // ═══════════════════════════════════════════════
  {
    id: 'dia7-desayuno',
    name: 'Pancakes de Avena y Banana (Sin Harina)',
    moment: 'desayuno',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '1 banana madura',
      '2 huevos',
      '½ taza de avena',
      '½ cdita de canela',
      'Pizca de sal',
      '½ taza de frutos rojos y 1 cdita de miel cruda',
    ],
    steps: [
      'Procesá en licuadora: banana, huevos, avena, canela y sal.',
      'Calentá sartén antiadherente con un toque de aceite.',
      'Volcá porciones de masa y cociná 2 min cada lado.',
      'Salen 4 panqueques.',
      'Servilos con frutos rojos y miel cruda.',
    ],
    tip: 'Sin harina, sin azúcar, sin mantequilla. La banana madura aporta almidón resistente que actúa como prebiótico para las bacterias buenas del colon.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥞',
    dietaryTags: { isGlutenFree: false, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia7-snack-am',
    name: 'Pera con Almendras',
    moment: 'snack',
    time: '1 min',
    difficulty: 'fácil',
    ingredients: [
      '1 pera bien madura',
      '8 almendras',
    ],
    steps: [
      'Lavá y cortá la pera en gajos.',
      'Acompañá con las almendras.',
      'Masticá despacio, disfrutando cada bocado.',
    ],
    tip: 'La fibra soluble de la pera madura es especialmente efectiva para nutrir tu microbiota. Un cierre perfecto para los 7 días del protocolo.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍐',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia7-almuerzo',
    name: 'Salmón con Ensalada Tibia de Espinaca',
    moment: 'almuerzo',
    time: '22 min',
    difficulty: 'media',
    ingredients: [
      '1 filete de salmón',
      'Limón y eneldo',
      '2 dientes de ajo en aceite de oliva',
      '2 tazas de espinaca',
      'Tomate cherry, palta en cubos, semillas de girasol',
    ],
    steps: [
      'Horneá el salmón 12 min con limón y eneldo a 200°C.',
      'En sartén, salteá ajo en aceite de oliva. Sumá la espinaca 1 min y apagá.',
      'Mezclá la espinaca con tomate cherry, palta y semillas de girasol.',
      'Aliñá con aceite de oliva + limón + sal.',
      'Serví el salmón sobre la ensalada tibia.',
    ],
    tip: 'Es tu tercer salmón de la semana: el mínimo recomendado de omega-3 para mantener la inflamación a raya de forma sostenida.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🐟',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },
  {
    id: 'dia7-snack-pm',
    name: 'Té Verde con Nueces de Brasil',
    moment: 'snack',
    time: '2 min',
    difficulty: 'fácil',
    ingredients: [
      '1 saquito de té verde',
      '2 nueces de Brasil',
      'Agua caliente',
    ],
    steps: [
      'Preparé el té verde con agua caliente (no hirviendo).',
      'Dejá infusionar 3 min.',
      'Acompañá con 2 nueces de Brasil.',
    ],
    tip: '2 nueces de Brasil tienen tu requerimiento diario de selenio, mineral antiinflamatorio que sostiene la tiroides. No comas más de 3 por día.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🍵',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'dia7-cena',
    name: 'Crema de Zanahoria con Jengibre y Huevo Duro',
    moment: 'cena',
    time: '20 min',
    difficulty: 'fácil',
    ingredients: [
      '4 zanahorias en rodajas',
      '1 trozo de jengibre',
      '1 diente de ajo, ½ cebolla',
      'Caldo o agua con sal',
      '1 huevo duro, semillas de sésamo',
    ],
    steps: [
      'Herví las zanahorias con jengibre, ajo y cebolla en caldo durante 18 min.',
      'Procesá todo hasta obtener una crema suave.',
      'Herví el huevo 10 min, pelá y picá.',
      'Serví la crema con el huevo duro picado arriba.',
      'Decorá con semillas de sésamo.',
    ],
    tip: 'La zanahoria cocida libera betacaroteno de forma más biodisponible. El jengibre cierra la semana con su acción procinética digestiva.',
    isExtra: false,
    isExpress: false,
    imageSlot: '🥕',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },


  // ═══════════════════════════════════════════════════════════════
  // RECETAS EXTRA (Bump) — 25 recetas del Recetario Anti-Inflamatorio
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'extra-01',
    name: 'Bowl de Yogur Antiinflamatorio',
    moment: 'desayuno',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '200 g de yogur natural sin azúcar (o yogur de coco)',
      '1 kiwi pelado y cortado en rodajas',
      '1 cucharada de semillas de chía',
      '1 cucharada de nueces picadas',
      '1 cucharadita de miel pura (opcional)',
      '½ cucharadita de cúrcuma en polvo',
      'Pizca de jengibre en polvo',
    ],
    steps: [
      'Volcá el yogur en un bowl amplio.',
      'Espolvoreá la cúrcuma y el jengibre sobre el yogur y mezclá suavemente.',
      'Distribuí las rodajas de kiwi sobre el yogur.',
      'Agregá las semillas de chía y las nueces.',
      'Rociá con la miel si deseás un toque dulce.',
      'Servir de inmediato o refrigerar 10 min para que la chía se hidrate.',
    ],
    tip: 'La combinación de chía + kiwi + cúrcuma es uno de los tríos más potentes para calmar la inflamación intestinal. El kiwi además mejora el tránsito en menos de 24 horas.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🥣',
    dietaryTags: { isGlutenFree: true, isDairyFree: false, isVegetarian: true },
  },
  {
    id: 'extra-02',
    name: 'Tostadas de Palta con Huevo y Cúrcuma',
    moment: 'desayuno',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '2 tostadas de pan sin gluten (de arroz o maíz)',
      '1 palta madura mediana',
      '2 huevos',
      '½ limón (jugo)',
      '½ cucharadita de cúrcuma en polvo',
      'Sal marina, pimienta negra',
      'Semillas de sésamo (opcional)',
    ],
    steps: [
      'Tostá el pan hasta que esté crocante.',
      'Pisá la palta con limón, sal y pimienta.',
      'Cociná los huevos en sartén con aceite de oliva, espolvoreando cúrcuma directamente.',
      'Extendé el puré de palta sobre cada tostada.',
      'Coroná con el huevo y las semillas de sésamo.',
    ],
    tip: 'La pimienta negra activa en un 2000% la biodisponibilidad de la curcumina. Siempre combiná cúrcuma con pimienta negra.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🍳',
    dietaryTags: { isGlutenFree: false, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'extra-03',
    name: 'Smoothie Verde Digestivo',
    moment: 'desayuno',
    time: '8 min',
    difficulty: 'fácil',
    ingredients: [
      '1 taza de espinaca fresca (o kale)',
      '½ pepino sin pelar',
      '1 rodaja de 2 cm de jengibre fresco',
      '½ manzana verde',
      'Jugo de ½ limón',
      '1 cucharada de semillas de lino molidas',
      '200 ml de agua de coco o agua filtrada',
    ],
    steps: [
      'Lavá bien la espinaca, el pepino y la manzana.',
      'Cortá el pepino y la manzana en trozos.',
      'Pelá el jengibre.',
      'Colocá todos los ingredientes en la licuadora: primero el líquido, luego los sólidos.',
      'Licuá a velocidad alta por 60 segundos.',
      'Serví de inmediato.',
    ],
    tip: 'El lino molido (no entero) libera sus ácidos grasos omega-3 directamente en el intestino. Guardá el lino molido en la heladera para que no se oxide.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🥤',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'extra-04',
    name: 'Avena Nocturna con Chía y Kiwi',
    moment: 'desayuno',
    time: '5 min + noche',
    difficulty: 'fácil',
    ingredients: [
      '½ taza de avena sin gluten certificada',
      '1 cucharada de semillas de chía',
      '200 ml de leche vegetal (almendras, avena o coco)',
      '1 kiwi',
      '1 cucharadita de extracto de vainilla',
      '1 cucharadita de miel (opcional)',
      'Pizca de canela',
    ],
    steps: [
      'Mezclá la avena con la chía, la leche vegetal, la vainilla y la canela en un frasco.',
      'Revolvé bien para que no queden grumos de chía.',
      'Tapá y llevá a la heladera por al menos 8 horas.',
      'A la mañana, sacá, revolvé y cortá el kiwi en rodajas.',
      'Servir la avena fría coronada con el kiwi.',
    ],
    tip: 'Remojar la avena reduce el ácido fítico, lo que mejora la absorción de zinc y magnesio: dos minerales clave para reducir la inflamación sistémica.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🥣',
    dietaryTags: { isGlutenFree: false, isDairyFree: false, isVegetarian: true },
  },
  {
    id: 'extra-05',
    name: 'Tortilla de Claras con Espinaca y Jengibre',
    moment: 'desayuno',
    time: '10 min',
    difficulty: 'media',
    ingredients: [
      '4 claras de huevo (o 3 huevos enteros)',
      '1 puñado grande de espinaca fresca',
      '½ cucharadita de jengibre fresco rallado',
      '1 diente de ajo pequeño',
      'Sal, pimienta negra',
      '1 cucharadita de aceite de oliva extra virgen',
    ],
    steps: [
      'Batí las claras con sal, pimienta y jengibre rallado hasta que estén espumosas.',
      'Calentá el aceite a fuego medio en sartén antiadherente.',
      'Saltear el ajo laminado 30 seg. Agregá la espinaca hasta que se marchite.',
      'Distribuí la espinaca y volcá las claras batidas encima.',
      'Cociná 3-4 min tapado a fuego bajo.',
      'Doblá al medio y servir.',
    ],
    tip: 'La espinaca aporta magnesio y antioxidantes que regulan el cortisol. Menos cortisol = menos inflamación sistémica.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🍳',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },


  {
    id: 'extra-06',
    name: 'Bowl de Salmón con Quinoa y Palta',
    moment: 'almuerzo',
    time: '10 min',
    difficulty: 'media',
    ingredients: [
      '150 g de salmón (filete)',
      '½ taza de quinoa',
      '½ palta',
      '½ taza de edamame congelado',
      '1 zanahoria rallada',
      'Jugo de 1 limón, aceite de oliva',
      '½ cucharadita de cúrcuma, semillas de sésamo',
    ],
    steps: [
      'Cocinar la quinoa: 1 taza de agua por ½ taza de quinoa, hervir 12-15 min.',
      'Condimentar el salmón con sal, pimienta y cúrcuma.',
      'Cocinar el salmón en sartén 3-4 min por lado. Desmenuzar.',
      'Cocinar el edamame 3 min en agua hirviendo.',
      'Armar el bowl: quinoa, salmón, palta, zanahoria y edamame.',
      'Aliñar con limón, aceite y semillas de sésamo.',
    ],
    tip: 'El salmón aporta EPA y DHA, los omega-3 más potentes para reducir la inflamación intestinal. Comelo al menos 3 veces por semana.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🐟',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },
  {
    id: 'extra-07',
    name: 'Wrap de Pollo con Hummus y Vegetales',
    moment: 'almuerzo',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '1 pechuga de pollo mediana (150 g)',
      '2 tortillas de maíz (o de arroz)',
      '3 cucharadas de hummus',
      '½ palta',
      '¼ pepino en bastones',
      'Lechuga o rúcula',
      '½ cucharadita de pimentón ahumado',
    ],
    steps: [
      'Condimentar el pollo con sal y pimentón ahumado. Cocinar en sartén 5-6 min por lado.',
      'Dejar reposar 2 min y cortar en tiras.',
      'Calentar las tortillas 30 seg en sartén seca.',
      'Untar cada tortilla con hummus generosamente.',
      'Distribuir pollo, pepino, palta y lechuga.',
      'Enrollar y servir.',
    ],
    tip: 'El hummus (garbanzo + aceite de oliva + ajo) combina proteína vegetal, grasas antiinflamatorias y compuestos sulfurados en un solo ingrediente.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🌯',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },
  {
    id: 'extra-08',
    name: 'Ensalada Tibia de Pollo, Mango y Palta',
    moment: 'almuerzo',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '150 g de pechuga de pollo en cubos',
      '½ mango maduro en cubos',
      '½ palta en cubos',
      '2 tazas de hojas verdes mixtas',
      '¼ cebolla morada en aros finos',
      'Jugo de 1 lima, aceite de oliva',
      '½ cucharadita de jengibre fresco rallado',
    ],
    steps: [
      'Condimentar el pollo con sal, pimienta y jengibre. Cocinar en sartén 5-6 min.',
      'Preparar la base de hojas verdes en el plato.',
      'Agregar la cebolla morada, el mango y la palta.',
      'Incorporar el pollo tibio encima.',
      'Mezclar jugo de lima + aceite de oliva + sal.',
      'Rociar el aliño y servir de inmediato.',
    ],
    tip: 'El mango contiene mangiferin, un antioxidante que inhibe vías inflamatorias específicas del intestino. La grasa de la palta mejora su absorción.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🥗',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },
  {
    id: 'extra-09',
    name: 'Pasta de Zapallitos al Pesto de Albahaca',
    moment: 'almuerzo',
    time: '10 min',
    difficulty: 'media',
    ingredients: [
      '2 zapallitos (zucchini) medianos',
      '1 taza de albahaca fresca',
      '2 cucharadas de nueces',
      '1 diente de ajo',
      '3 cucharadas de aceite de oliva extra virgen',
      'Jugo de ½ limón, sal y pimienta',
      'Tomates cherry (opcional)',
    ],
    steps: [
      'Hacé los fideos de zapallito con pelapapas de juliana o espiralizador.',
      'Para el pesto: procesá albahaca + nueces + ajo + aceite + limón + sal.',
      'Saltear los zapallitos en sartén 3-4 min. Deben quedar al dente.',
      'Retirar del fuego y mezclar con el pesto.',
      'Agregar tomates cherry cortados si usás.',
      'Servir de inmediato.',
    ],
    tip: 'El zapallito reemplaza la pasta de trigo eliminando el gluten y el pico glucémico, dos de los principales disparadores de inflamación intestinal.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🍝',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'extra-10',
    name: 'Tacos de Lechuga con Pavo y Guacamole',
    moment: 'almuerzo',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '150 g de carne picada de pavo (o pollo)',
      '8 hojas grandes de lechuga romana',
      '1 palta para guacamole',
      '1 tomate mediano en cubos',
      '¼ cebolla morada picada',
      'Jugo de 1 limón, comino, pimentón',
      'Cilantro fresco (opcional)',
    ],
    steps: [
      'Cocinar la carne con sal, comino y pimentón 8-10 min, rompiendo grumos.',
      'Pisar la palta con tomate, cebolla, limón y sal para el guacamole.',
      'Lavar y secar las hojas de lechuga.',
      'Distribuir la carne caliente en cada hoja.',
      'Agregar una cucharada de guacamole encima.',
      'Terminar con cilantro y cebolla al gusto.',
    ],
    tip: 'Usar lechuga en lugar de tortilla de trigo elimina el gluten y agrega fibra soluble que alimenta tu microbiota positiva.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🌮',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },


  {
    id: 'extra-11',
    name: 'Salmón al Horno con Espárragos',
    moment: 'cena',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '1 filete de salmón (150-180 g)',
      '1 atado de espárragos frescos',
      '2 dientes de ajo laminados',
      'Jugo de ½ limón',
      '1 cucharada de aceite de oliva',
      '½ cucharadita de cúrcuma',
      'Sal, pimienta y eneldo seco',
    ],
    steps: [
      'Precalentar el horno a 200°C.',
      'Lavar y cortar los extremos duros de los espárragos.',
      'Colocar salmón y espárragos en fuente forrada con papel.',
      'Rociar aceite, exprimir limón, distribuir ajo, cúrcuma, sal y pimienta.',
      'Hornear 15-18 min hasta que el salmón se desmigue fácilmente.',
      'Servir con una rodaja de limón fresca.',
    ],
    tip: 'Los espárragos son prebióticos naturales: alimentan las bacterias del colon que producen ácidos grasos de cadena corta, apagando la inflamación.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🐟',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },
  {
    id: 'extra-12',
    name: 'Pollo al Limón con Vegetales Asados',
    moment: 'cena',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '1 pechuga de pollo mediana',
      '1 zucchini en rodajas',
      '1 morrón rojo en tiras',
      '½ berenjena en cubos',
      '1 limón (jugo + ralladura)',
      'Aceite de oliva, orégano, cúrcuma',
    ],
    steps: [
      'Precalentar el horno a 200°C.',
      'Marinar el pollo con limón, aceite, cúrcuma, sal y pimienta.',
      'Distribuir los vegetales en fuente con aceite y orégano.',
      'Colocar el pollo en el centro con vegetales alrededor.',
      'Hornear 20-22 min, dando vuelta a mitad de cocción.',
      'Verificar cocción del pollo y servir.',
    ],
    tip: 'El morrón rojo tiene más vitamina C que una naranja: fundamental para la síntesis de colágeno intestinal y reparación de la mucosa digestiva.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🍗',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },
  {
    id: 'extra-13',
    name: 'Zapallo Relleno de Quinoa y Vegetales',
    moment: 'cena',
    time: '10 min',
    difficulty: 'media',
    ingredients: [
      '1 zapallo tipo butternut pequeño',
      '½ taza de quinoa cocida',
      '½ morrón rojo picado',
      '½ cebolla picada',
      '1 puñado de espinaca fresca',
      '1 diente de ajo',
      'Comino, cúrcuma, sal, aceite de oliva',
    ],
    steps: [
      'Cortar el zapallo al medio y cocinar en microondas 8-10 min hasta blandura.',
      'Retirar un poco de pulpa del centro y picarla.',
      'Saltear ajo + cebolla + morrón 5 min.',
      'Agregar la pulpa picada, espinaca, comino y cúrcuma. Cocinar 3 min.',
      'Incorporar la quinoa cocida y mezclar. Salpimentar.',
      'Rellenar las mitades de zapallo y gratinar 5 min.',
    ],
    tip: 'El zapallo aporta betacaroteno que el cuerpo convierte en vitamina A, esencial para mantener la integridad de la mucosa intestinal.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🎃',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'extra-14',
    name: 'Sopa Antiinflamatoria de Cúrcuma y Jengibre',
    moment: 'cena',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '1 taza de caldo de verduras bajo en sodio',
      '1 taza de leche de coco',
      '½ cebolla picada, 2 dientes de ajo',
      '1 rodaja de 3 cm de jengibre fresco',
      '1 cucharadita de cúrcuma en polvo',
      '1 zanahoria en trozos',
      '½ taza de lentejas rojas',
      'Jugo de ½ limón, sal, pimienta, aceite de oliva',
    ],
    steps: [
      'Dorar cebolla y ajo con aceite 3 min.',
      'Agregar jengibre rallado y cúrcuma, cocinar 1 min.',
      'Incorporar zanahoria, lentejas rojas y caldo. Hervir.',
      'Bajar fuego y cocinar 15 min hasta que las lentejas estén blandas.',
      'Agregar la leche de coco y jugo de limón. Cocinar 3 min más.',
      'Mixear con minipimer si se desea cremosa. Salpimentar.',
    ],
    tip: 'La sopa caliente con jengibre + cúrcuma + leche de coco tiene la mayor concentración de compuestos antiinflamatorios por porción. Ideal como cena liviana.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🍲',
    dietaryTags: { isGlutenFree: true, isDairyFree: false, isVegetarian: true },
  },
  {
    id: 'extra-15',
    name: 'Pescado Blanco con Puré de Coliflor',
    moment: 'cena',
    time: '10 min',
    difficulty: 'media',
    ingredients: [
      '150-180 g de merluza o tilapia',
      '1 taza de coliflor en floretes',
      '1 cucharada de aceite de oliva',
      '½ cucharadita de cúrcuma',
      '1 diente de ajo',
      'Jugo de ½ limón, perejil fresco',
      'Pizca de nuez moscada',
    ],
    steps: [
      'Hervir coliflor 12-15 min hasta que esté muy blanda. Escurrir.',
      'Procesar la coliflor con ajo, aceite, nuez moscada, sal y pimienta.',
      'Condimentar el pescado con sal, pimienta y cúrcuma.',
      'Cocinar en sartén 3-4 min por lado.',
      'Servir puré de base con el filete encima.',
      'Terminar con limón y perejil picado.',
    ],
    tip: 'El puré de coliflor reemplaza al de papa con la mitad de carbohidratos y triple de sulforafano, compuesto que activa genes de defensa antioxidante.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🐟',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: false },
  },


  {
    id: 'extra-16',
    name: 'Hummus Casero con Bastones de Zanahoria',
    moment: 'snack',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '1 lata (400 g) de garbanzos cocidos',
      '2 cucharadas de aceite de oliva extra virgen',
      '1 diente de ajo',
      'Jugo de 1 limón',
      '1 cucharada de tahini',
      '½ cucharadita de comino',
      'Sal, pimienta y 2 zanahorias',
    ],
    steps: [
      'Cortar zanahorias en bastones y reservar en agua fría.',
      'Procesar garbanzos, ajo, limón, tahini y comino.',
      'Agregar aceite en hilo fino mientras procesa.',
      'Si queda espeso, agregar 2-3 cdas de aquafaba.',
      'Ajustar sal, pimienta y limón.',
      'Servir con bastones de zanahoria.',
    ],
    tip: 'Los garbanzos son ricos en butirato (preforma), que nutre directamente las células del colon. El tahini aporta calcio y vitamina E antioxidante.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🥕',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'extra-17',
    name: 'Mix de Frutos Secos con Cúrcuma',
    moment: 'snack',
    time: '5 min',
    difficulty: 'fácil',
    ingredients: [
      '8 nueces (mitades)',
      '10 almendras crudas',
      '1 cucharada de semillas de girasol',
      '1 cucharada de arándanos secos sin azúcar',
      '½ cucharadita de cúrcuma en polvo',
      'Pizca de canela',
      'Pizca de sal marina',
    ],
    steps: [
      'Mezclar todos los frutos secos en un bowl.',
      'Espolvorear la cúrcuma y la canela.',
      'Revolver bien para cubrir los frutos secos.',
      'Servir o guardar en frasco hermético hasta 5 días.',
    ],
    tip: 'Las nueces son la única nuez que contiene ALA (omega-3 vegetal). Comer 7-10 nueces al día reduce los marcadores de inflamación en sangre.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🥜',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'extra-18',
    name: 'Chips de Batata al Horno',
    moment: 'snack',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '1 batata (camote) mediana',
      '1 cucharada de aceite de oliva',
      '½ cucharadita de pimentón ahumado',
      '½ cucharadita de ajo en polvo',
      'Sal marina y pimienta',
    ],
    steps: [
      'Precalentar el horno a 200°C.',
      'Lavar la batata (no pelar si la piel está limpia).',
      'Cortar en rodajas muy finas (2-3 mm) con cuchillo o mandolina.',
      'Mezclar con aceite, pimentón, ajo en polvo, sal y pimienta.',
      'Distribuir en placa sin superponer.',
      'Hornear 15-18 min, dando vuelta a mitad de cocción.',
    ],
    tip: 'La batata tiene índice glucémico más bajo que la papa y aporta betacaroteno, potente antiinflamatorio natural.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🍠',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'extra-19',
    name: 'Yogur con Kiwi y Nueces',
    moment: 'snack',
    time: '5 min',
    difficulty: 'fácil',
    ingredients: [
      '150 g de yogur natural sin azúcar (o kéfir)',
      '1 kiwi pelado y en cubos',
      '6 mitades de nueces',
      '1 cucharadita de semillas de chía',
      '1 cucharadita de miel (opcional)',
    ],
    steps: [
      'Verter el yogur o kéfir en un vaso o bowl.',
      'Colocar el kiwi en cubos encima.',
      'Agregar las nueces y las semillas de chía.',
      'Terminar con un hilo de miel si se desea.',
      'Consumir de inmediato.',
    ],
    tip: 'El kéfir tiene entre 10 y 34 cepas probióticas vivas, versus 2-3 del yogur común. Es el snack más amigable para la microbiota.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🥝',
    dietaryTags: { isGlutenFree: true, isDairyFree: false, isVegetarian: true },
  },
  {
    id: 'extra-20',
    name: 'Galletas de Avena y Plátano (3 Ingredientes)',
    moment: 'snack',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '1 plátano (banana) muy maduro',
      '1 taza de avena sin gluten certificada',
      '1 cucharada de semillas de chía',
      'Opcionales: cacao en polvo, canela, nueces picadas',
    ],
    steps: [
      'Precalentar el horno a 180°C.',
      'Pisar el plátano con tenedor hasta obtener puré liso.',
      'Mezclar con la avena y la chía. Agregar opcionales.',
      'Formar bolitas y aplastar sobre placa con papel.',
      'Hornear 12-15 min hasta bordes dorados.',
      'Dejar enfriar 5 min (quedan más firmes al enfriar).',
    ],
    tip: 'Sin azúcar, harina ni mantequilla. El plátano maduro aporta almidón resistente que actúa como prebiótico, alimentando las bacterias buenas del colon.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🍪',
    dietaryTags: { isGlutenFree: false, isDairyFree: true, isVegetarian: true },
  },


  {
    id: 'extra-21',
    name: 'Té de Jengibre y Limón',
    moment: 'snack',
    time: '10 min',
    difficulty: 'fácil',
    ingredients: [
      '1 rodaja de 3 cm de jengibre fresco pelado',
      'Jugo de ½ limón',
      '300 ml de agua',
      '1 cucharadita de miel pura (opcional)',
      'Pizca de cúrcuma + pimienta negra (opcional)',
    ],
    steps: [
      'Llevar el agua a hervor.',
      'Rallar o laminar el jengibre en una taza.',
      'Verter el agua hirviendo sobre el jengibre. Reposar 5 min.',
      'Colar si se desea.',
      'Agregar limón y miel una vez tibio.',
      'Beber caliente o tibio.',
    ],
    tip: 'Tomar esta infusión en ayunas activa la producción de bilis y estimula la motilidad intestinal. El gingerol del jengibre fresco es 6x más potente que el polvo.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🍵',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'extra-22',
    name: 'Agua Detox con Pepino y Menta',
    moment: 'snack',
    time: '5 min',
    difficulty: 'fácil',
    ingredients: [
      '1 litro de agua filtrada fría',
      '½ pepino en rodajas finas',
      '8-10 hojas de menta fresca',
      '1 limón en rodajas',
      'Rodaja de jengibre fresco (opcional)',
      'Hielo al gusto',
    ],
    steps: [
      'Lavar pepino, limón y menta.',
      'Cortar pepino y limón en rodajas finas sin pelar.',
      'Colocar todo en una jarra de 1 litro.',
      'Agregar agua fría y hielo.',
      'Macerar en heladera al menos 1 hora (ideal 3-4 horas).',
      'Beber durante el día.',
    ],
    tip: 'El pepino tiene cucurbitacinas que inhiben vías inflamatorias. Su mayor beneficio: te ayuda a tomar más agua, y la hidratación correcta es el primer paso para desinflamar.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🥒',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'extra-23',
    name: 'Golden Milk (Leche Dorada)',
    moment: 'snack',
    time: '8 min',
    difficulty: 'fácil',
    ingredients: [
      '250 ml de leche vegetal (almendras, coco o avena)',
      '1 cucharadita de cúrcuma en polvo',
      '½ cucharadita de canela en polvo',
      '¼ cucharadita de jengibre en polvo',
      'Pizca generosa de pimienta negra',
      '1 cucharadita de miel o dátil picado',
    ],
    steps: [
      'Calentar la leche vegetal a fuego bajo-medio sin hervir.',
      'Agregar cúrcuma, canela, jengibre y pimienta negra.',
      'Mezclar con batidor hasta que no queden grumos.',
      'Mantener a fuego bajo 3-4 min.',
      'Retirar del fuego, agregar miel una vez tibio.',
      'Servir en taza grande y beber tibio.',
    ],
    tip: 'La bebida antiinflamatoria más estudiada del mundo. Curcumina + piperina + grasa de leche de coco = máxima biodisponibilidad. Antes de dormir potencia la recuperación intestinal.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🥛',
    dietaryTags: { isGlutenFree: false, isDairyFree: false, isVegetarian: true },
  },
  {
    id: 'extra-24',
    name: 'Smoothie de Papaya Digestiva',
    moment: 'desayuno',
    time: '8 min',
    difficulty: 'fácil',
    ingredients: [
      '1 taza de papaya madura en cubos',
      '½ plátano maduro',
      '1 cucharada de semillas de chía',
      '200 ml de agua de coco',
      'Jugo de ½ limón',
      '½ cucharadita de jengibre fresco rallado',
    ],
    steps: [
      'Pelar la papaya y quitarle las semillas.',
      'Colocar todos los ingredientes en la licuadora.',
      'Licuar a velocidad alta 60 segundos.',
      'Ajustar: más limón para acidez, más plátano para dulce.',
      'Verter en vaso alto con hielo.',
      'Consumir de inmediato para preservar enzimas.',
    ],
    tip: 'La papaya contiene papaína, enzima que descompone proteínas inflamatorias en el intestino. Especialmente útil después de comidas proteicas.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🥤',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
  {
    id: 'extra-25',
    name: 'Infusión de Hinojo y Manzanilla',
    moment: 'snack',
    time: '8 min',
    difficulty: 'fácil',
    ingredients: [
      '1 cucharadita de semillas de hinojo (o bolsita de té)',
      '1 bolsita de manzanilla (o flores secas)',
      '300 ml de agua',
      '1 cucharadita de miel pura (opcional)',
      'Pizca de anís estrellado (opcional)',
    ],
    steps: [
      'Hervir el agua.',
      'Colocar semillas de hinojo y manzanilla en una taza.',
      'Verter el agua y cubrir con un platito.',
      'Dejar reposar 7 minutos mínimo.',
      'Colar y agregar miel una vez tibio.',
      'Beber lentamente como ritual nocturno.',
    ],
    tip: 'El hinojo contiene anetol, un compuesto que relaja la musculatura del colon en menos de 20 minutos. Con manzanilla (ansiolítica natural) es la mejor bebida para terminar el día sin gases.',
    isExtra: true,
    isExpress: true,
    imageSlot: '🫖',
    dietaryTags: { isGlutenFree: true, isDairyFree: true, isVegetarian: true },
  },
];

// ═══════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════

export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find((r) => r.id === id);
}

export function getRecipesByMoment(moment: Moment): Recipe[] {
  return recipes.filter((r) => r.moment === moment);
}

export function getBasicRecipes(): Recipe[] {
  return recipes.filter((r) => !r.isExtra);
}

export function getExtraRecipes(): Recipe[] {
  return recipes.filter((r) => r.isExtra);
}
